"""Fact engine: normalized chess facts over a frame tree (design `docs/design/fact-engine-a0-design.md`).

This package is the redesign; it never imports the legacy MVP modules (`tests/test_package_boundaries.py`).
"""

from calliope.facts.engine import FactEngine
from calliope.facts.errors import (
    BudgetExceededError,
    FactEngineError,
    IllegalMoveError,
    InvalidPositionError,
    InvalidRequestError,
    UnsupportedVariantError,
)
from calliope.facts.families.delta import (
    DeltaFacts,
    FlagChange,
    PieceFlags,
    PiecePair,
    PinRelation,
    SetChange,
)
from calliope.facts.families.geometry import Pin, Relation
from calliope.facts.families.material import MaterialFacts
from calliope.facts.families.move import Capture, MoveFacts, Promotion
from calliope.facts.families.pattern_delta import (
    DefenceEnded,
    DefenceEndReason,
    LineTriple,
    PatternDeltaFacts,
    TargetSetChange,
)
from calliope.facts.families.patterns import (
    LinePattern,
    MultiTargetAttack,
    Order,
    PatternsFacts,
    Target,
)
from calliope.facts.families.pieces import PIECE_ORDER_RANK, PieceFacts, PiecesFacts
from calliope.facts.families.status import StatusFacts
from calliope.facts.flow import (
    MaterialFlow,
    PlyMaterial,
    Stable,
    Unstable,
    UnstableReason,
    material_flow,
)
from calliope.facts.keys import Color, NodeId, PieceId, PieceType, PositionKey, RootId
from calliope.facts.planning import planned_search_bound
from calliope.facts.request import (
    EXPLORED,
    FULL,
    NONE,
    PLAYED,
    EnsureRequest,
    ExpansionSpec,
    ExtendRequest,
    InputLine,
    LineRole,
    OpenRequest,
    RoleKind,
    RootSpec,
    SessionBudget,
    analysis,
)
from calliope.facts.search.profile import EngineProfile
from calliope.facts.search.records import Cp, EngineLineFact, EngineSearch, Mate, SearchKind, Wdl
from calliope.facts.tree import (
    EngineLineId,
    FactTree,
    FrameNode,
    LineEnd,
    LineId,
    LineRecord,
    NodeSearch,
    SearchScore,
    Terminal,
    TerminalKind,
    TreeView,
    order,
)
from calliope.facts.values import Absent, Defined, NotApplicable, NotComputed, Unavailable

__all__ = [
    "EXPLORED",
    "FULL",
    "NONE",
    "PIECE_ORDER_RANK",
    "PLAYED",
    "Absent",
    "BudgetExceededError",
    "Capture",
    "Color",
    "Cp",
    "DefenceEndReason",
    "DefenceEnded",
    "Defined",
    "DeltaFacts",
    "EngineLineFact",
    "EngineLineId",
    "EngineProfile",
    "EngineSearch",
    "EnsureRequest",
    "ExpansionSpec",
    "ExtendRequest",
    "FactEngine",
    "FactEngineError",
    "FactTree",
    "FlagChange",
    "FrameNode",
    "IllegalMoveError",
    "InputLine",
    "InvalidPositionError",
    "InvalidRequestError",
    "LineEnd",
    "LineId",
    "LinePattern",
    "LineRecord",
    "LineRole",
    "LineTriple",
    "Mate",
    "MaterialFacts",
    "MaterialFlow",
    "MoveFacts",
    "MultiTargetAttack",
    "NodeId",
    "NodeSearch",
    "NotApplicable",
    "NotComputed",
    "OpenRequest",
    "Order",
    "PatternDeltaFacts",
    "PatternsFacts",
    "PieceFacts",
    "PieceFlags",
    "PieceId",
    "PiecePair",
    "PieceType",
    "PiecesFacts",
    "Pin",
    "PinRelation",
    "PlyMaterial",
    "PositionKey",
    "Promotion",
    "Relation",
    "RoleKind",
    "RootId",
    "RootSpec",
    "SearchKind",
    "SearchScore",
    "SessionBudget",
    "SetChange",
    "Stable",
    "StatusFacts",
    "Target",
    "TargetSetChange",
    "Terminal",
    "TerminalKind",
    "TreeView",
    "Unavailable",
    "Unstable",
    "UnstableReason",
    "UnsupportedVariantError",
    "Wdl",
    "analysis",
    "material_flow",
    "order",
    "planned_search_bound",
]
