"""Board deltas, tactical candidates, counterfactuals, and explanation evidence."""

from calliope.domain.analysis.bad_move import (
    BadMoveCauseKind,
    BadMoveCauseResult,
    BadMoveCauseStatus,
    BadMoveExplanationResult,
    BadMoveExplanationStatus,
    BasePieceRef,
    MateEvidenceLevel,
    MaterialLineEvidence,
)
from calliope.domain.analysis.counterfactual import (
    CounterfactualBatchRequest,
    CounterfactualBatchResult,
    CounterfactualProbe,
    ProbeKind,
    ProbeResult,
    TerminalKind,
    TerminalOutcome,
)
from calliope.domain.analysis.delta import (
    AttackChange,
    BoardDelta,
    CaptureDelta,
    CheckChange,
    CheckChangeKind,
    DefenseChange,
    MaterialChange,
    PieceCorrespondence,
    PieceTransition,
    PieceTransitionKind,
    RelationChangeKind,
)
from calliope.domain.analysis.good_move import (
    AlternativeScope,
    GoodMoveBenefitKind,
    GoodMoveBenefitResult,
    GoodMoveBenefitStatus,
    GoodMoveExplanationResult,
    GoodMoveExplanationStatus,
    GoodMoveMode,
    RepresentativeAlternative,
)
from calliope.domain.analysis.tactics import (
    TacticalCandidate,
    TacticalCandidateKind,
    TacticalCandidateStatus,
    TacticalDetection,
)

__all__ = [
    "AlternativeScope",
    "AttackChange",
    "BadMoveCauseKind",
    "BadMoveCauseResult",
    "BadMoveCauseStatus",
    "BadMoveExplanationResult",
    "BadMoveExplanationStatus",
    "BasePieceRef",
    "BoardDelta",
    "CaptureDelta",
    "CheckChange",
    "CheckChangeKind",
    "CounterfactualBatchRequest",
    "CounterfactualBatchResult",
    "CounterfactualProbe",
    "DefenseChange",
    "GoodMoveBenefitKind",
    "GoodMoveBenefitResult",
    "GoodMoveBenefitStatus",
    "GoodMoveExplanationResult",
    "GoodMoveExplanationStatus",
    "GoodMoveMode",
    "MateEvidenceLevel",
    "MaterialChange",
    "MaterialLineEvidence",
    "PieceCorrespondence",
    "PieceTransition",
    "PieceTransitionKind",
    "ProbeKind",
    "ProbeResult",
    "RelationChangeKind",
    "RepresentativeAlternative",
    "TacticalCandidate",
    "TacticalCandidateKind",
    "TacticalCandidateStatus",
    "TacticalDetection",
    "TerminalKind",
    "TerminalOutcome",
]
